### ISSUE TITLE
HW: kicad file for IPS board missing sockets for Teensy

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#67]
This is probably historical since earlier to envisioned soldering the Teensy on, but better having sockets.

**Comment by gzweigle** [comment]
When I created the schematic for IPS I didn't realize that using a symbol for both Teensy and SCA would later cause problems with specifying the headers. So, instead of redoing the schematic, as a workaround, I had decided to just specify the sockets in the bill of materials:
https://github.com/gzweigle/DIY-Grand-Digital-Piano/blob/main/hardware/releases/ips20/ips20_bill_of_materials_0.txt.
Because of the workaround, I am going to close this issue. Feel free to re-open if the answer isn't sufficient. However, unless this change is a showstopper for creating boards, it will be a very low priority.  I will also add to the IPS 2.1 project to-do.
